### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [vrd/kottans-js-2016#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by vrd** [comment]
https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html

**Comment by mkozhukharenko** [comment]
https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L50-L55 this shouldn't be inside a `nav`

**Comment by mkozhukharenko** [comment]
https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L50-L55 remove table and use some other elements. You can try a `meter`

the same https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L137-L139

don't use table is a UI element don't look like a table.

**Comment by mkozhukharenko** [comment]
👍  for `sup`

**Comment by mkozhukharenko** [comment]
https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L87-L92 it isn't a small

read about usage of a [small element ](http://html5doctor.com/small-hr-element/)

the same https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L100-L108

**Comment by mkozhukharenko** [comment]
I would use `figure` along with `figcapion` for this 
https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L235-L236

**Comment by mkozhukharenko** [comment]
it can be an article https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L325-L330

see https://github.com/m1n0s/kottans-js-2016/issues/2#issuecomment-220844681

**Comment by mkozhukharenko** [comment]
I'd use an `aside` https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L332

**Comment by mkozhukharenko** [comment]
Is can be a nav a well. https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L504-L508 What do you think? 
Could you read few articles about a `nav` element and make a short list of argument why that element should/shouldn't be a `nav`, please?

**Comment by mkozhukharenko** [comment]
can it be an article? what do you think? https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L161-L170

**Comment by vrd** [comment]
> https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L50-L55 this shouldn't be inside a nav

Agree with that, it's more advertising content than navigation. I moved specprojects to aside and now its noname section wrapper outside nav and aside - not so cool...

**Comment by vrd** [comment]
> https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L50-L55 remove table and use some other elements. You can try a meter
> the same https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L137-L139
> don't use table is a UI element don't look like a table.

Strongly disagree with that. At first, meter has very limited usage - it's only suitable to display a value inside defined range (karma doesn't have max limit - so range is undefined). If you do not specify range it will be [0,1] automatically and value must be inside this range - that's in standard.
At second, this UI element **definitely** looks like table. It has three _columns_ and every column has own header (Пользователь, Карма, Рейтинг) in second row and value (@rayproud, 2.0, 0.0) in first row! (usually column header is located above value, but here it's vice versa - nevertheless it's still a table). If there was some element to display any numeric value I would use it, but I not found something like this in standard.

**Comment by vrd** [comment]
> https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L87-L92 it isn't a small
> read about usage of a small element
> the same https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L100-L108

Yes, such usage of small element doen't comply with standard. Changed from small to aside.

**Comment by mkozhukharenko** [comment]
> Strongly disagree with that. At first, meter has very limited usage - it's only suitable to display a value inside defined range (karma doesn't have max limit - so range is undefined). If you do not specify range it will be [0,1] automatically and value must be inside this range - that's in standard.

I see you point. Since this question is a matter of dispute it's fine if you pick an option that you like. 

But about this markup

``` html
            <table>
              <tr>  <td>                            <td>карма <td>рейтинг
              <tr>  <td><a href=...>@rayproud</a>   <td>2,0   <td>0,0                
            </table>
```

I'm afraid I disagree.
Is this a table? 
![image](https://cloud.githubusercontent.com/assets/9365923/15479338/688d60b4-2128-11e6-9f28-9755b7b9721e.png)
Is you want to  insist on your point I'll give another argument: It's much harder to style a table that simple divs.

it looks like a table:
![image](https://cloud.githubusercontent.com/assets/9365923/15479498/29856dca-2129-11e6-9740-670b049cab35.png)

**Comment by vrd** [comment]
> I would use figure along with figcapion for this 
> https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L235-L236

Interesting idea, changed to figure.

**Comment by mkozhukharenko** [comment]
be careful with using a figure ([source](http://html5doctor.com/avoiding-common-html5-mistakes/#figure))

**Comment by vrd** [comment]
> it can be an article https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L325-L330
> see m1n0s/kottans-js-2016#2 (comment)

Yes it makes sense, also read about proper use of aside and change my mind about it. Aside is not a sidebar or wrapper for random stuff - it's container for secondary content (secondary to main article or website)!

**Comment by vrd** [comment]
> Is can be a nav a well. https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L504-L508 What do you think? 
> Could you read few articles about a nav element and make a short list of argument why that element >should/shouldn't be a nav, please?

Best article I found is a part of same article you send me about figures [nav](http://html5doctor.com/avoiding-common-html5-mistakes/#nav-external)

Why it should be a nav:
- It is a group of links to other pages

Why it shouldn't be a nav:
- It is not a major navigation block (primary or secondary navigation)
- It's not an in-page navigation
- Links located in footer (with a lot of other links and near <small> copyright text - it's like dark corner of basement)
- It's social links (could be nav in profile-style personal homepage but not in big website like this)

**Comment by vrd** [comment]
> can it be an article? what do you think? https://github.com/vrd/kottans-js-2016/blob/master/week01/lec1/habr.html#L161-L170

![image](https://cloud.githubusercontent.com/assets/10587773/15485029/b4ae06fc-2145-11e6-91d5-8e04f8573488.png)

It is a good question. According to standard article is `independently distributable or reusable` composition. Could a news heading with some stats be a such composition? From one point of view it is very small content - not a blogpost not a comment not an article literally. And here it is just an one item from list of similar items (maybe this list is an article?). We can say it's not a content it's only a _link_ to a content, so it's not an article.

But from other side, this is can be viewed as separate content - heading contains some information from article, and stats illustrate how popular this particular article is. One could use this block in different lists at website or in email/newsletter as independent content. So this block could be an article.

IMHO, if page is content-rich (contains longread articles, comments, asides, etc) it is not a good idea to use article element for such small parts of content as every heading of article from list of articles related to main article of current page. But if main content of page is exactly a list of headings with some stats, maybe article elements could be used for every heading.

**Comment by mkozhukharenko** [comment]
good research! 👍
