### ISSUE TITLE
Домашнее задание по тестированию

### ISSUE THREAD

**Issue by tiny-kottan** [vrd/kottans-js-2016#7]
https://github.com/timoxley/functional-javascript-workshop - complete 'Function Spies' exercise.
Investigate following questions:
  1) What are stubs, mocks? What is the difference?
  2) What is the difference between TDD and BDD?
Read about several test frameworks / setups, pick one (qunit, jasmine, mocha, ava, tape). 
Do Kata #1 using it.

**Comment by vrd** [comment]
Function Spy: https://github.com/vrd/kottans-js-2016/blob/master/week05/lec01/funcjs/spy.js

Answers:
1) Stubs and mocks represent entities that are supposed to interact with tested entity during test process. Usually stubs and mocks have functionality limited only to necessary functionality for specific test. Difference between stubs and mocks: stub specifies only answers to test entity calls, mock specifies answers and order of test entity calls.
2) TDD is more global term that describes a paradigm of development based on testing. BDD is subclass of TDD. BDD says that tests must be aimed at first to verify correct behavior of tested entity during test (order of events, calls to other modules) but not only to check state of tested and external entities at the end of test.

Kata1:
calc.js https://github.com/vrd/kottans-js-2016/blob/master/week05/lec01/calc.js
test.js https://github.com/vrd/kottans-js-2016/blob/master/week05/lec01/test.js
