### ISSUE TITLE
Домашнее задание по Node

### ISSUE THREAD

**Issue by tiny-kottan** [vrd/kottans-js-2016#8]
Complete https://gist.github.com/mkozhukharenko/74c2d55ff53f67670a6a7e1f0c37f1b0

**Comment by vrd** [comment]
@mkozhukharenko
class App(): https://github.com/vrd/kottans-js-2016/blob/master/week06/lec2/app.js
index.js: https://github.com/vrd/kottans-js-2016/blob/master/week06/lec2/index.js
